services:
  app:
    image: shouravawasthi/devops-build:latest
    ports:
      - "80:80"
    restart: always

  prometheus:
    build:
      context: .
      dockerfile: Dockerfile.prometheus
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: always

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    ports:
      - "9115:9115"
    restart: always